import { useEffect, useState } from "react";
import { apiClient, type ExportSummary, type HandbookSummary } from "../api/client.js";
type ExportWorkspaceProps = { childId: string; canEdit: boolean; loadHandbooks?: (childId: string) => Promise<HandbookSummary[]>; loadExports?: (childId: string) => Promise<ExportSummary[]>; readOnly?: boolean };
export function ExportWorkspace({ childId, canEdit, loadHandbooks = apiClient.handbooks, loadExports = apiClient.exports, readOnly = false }: ExportWorkspaceProps) {
  const [handbooks, setHandbooks] = useState<HandbookSummary[]>([]); const [exports, setExports] = useState<ExportSummary[]>([]); const [open, setOpen] = useState(false); const [handbookId, setHandbookId] = useState(""); const [kind, setKind] = useState<"screen" | "print">("screen");
  const reload = async () => { const [nextHandbooks, nextExports] = await Promise.all([loadHandbooks(childId), loadExports(childId)]); setHandbooks(nextHandbooks); setExports(nextExports); setHandbookId(current => current || nextHandbooks[0]?.id || ""); };
  useEffect(() => { void reload(); }, [childId]);
  return <section className="export-view" aria-label="导出文件"><header><b>已生成文件</b>{canEdit && !readOnly && <button onClick={() => setOpen(true)}>导出手册</button>}</header>{open && <form onSubmit={async e => { e.preventDefault(); await apiClient.createExport(childId, { handbookId, kind }); setOpen(false); await reload(); }}><select aria-label="选择观察手册" value={handbookId} onChange={e => setHandbookId(e.target.value)}>{handbooks.map(h => <option key={h.id} value={h.id}>{h.title}</option>)}</select><label><input type="radio" checked={kind === "screen"} onChange={() => setKind("screen")} />屏幕 PDF</label><label><input type="radio" checked={kind === "print"} onChange={() => setKind("print")} />印刷 PDF（3mm 出血）</label><button type="submit">确认生成</button></form>}<div className="export-list">{exports.map(job => <article key={job.id}><b>{job.kind === "screen" ? "屏幕 PDF" : "印刷 PDF"}</b>{readOnly ? <span className="demo-readonly-label">公开示例 · 仅供浏览</span> : <a href={`/api/exports/${job.id}/download`}>下载</a>}{canEdit && !readOnly && <button onClick={async () => { await apiClient.removeExport(job.id); await reload(); }}>删除</button>}</article>)}</div></section>;
}
