import { useState } from "react";
import { ApiError, apiClient } from "../api/client.js";

export function LoginPage({ onAuthenticated, onDemo }: { onAuthenticated?: () => void; onDemo?: () => void }) {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [familyName, setFamilyName] = useState("");
  const [childName, setChildName] = useState("");
  const [mode, setMode] = useState<"login" | "register">("login");
  const [notice, setNotice] = useState("");
  return <main className="login-page"><section className="login-panel"><div className="login-mark">O</div><p className="login-eyebrow">家庭观察档案</p><h1>把成长，收进一册温柔的记录。</h1><p>{mode === "login" ? "登录后管理孩子的观察、主题手册与出版文件。" : "为家庭创建一间共同使用的观察档案室。"}</p><button className="demo-entry" type="button" onClick={onDemo}>浏览完整示例档案 →</button><form onSubmit={async event => { event.preventDefault(); if (mode === "register" && password.length < 8) { setNotice("密码至少需要 8 位，请换一个更安全的密码。"); return; } try { if (mode === "login") await apiClient.login(username, password); else await apiClient.register({ username, password, familyName, childName }); setNotice(mode === "login" ? "登录成功，正在进入档案室…" : "家庭档案已创建，正在进入…"); onAuthenticated?.(); } catch (error) { setNotice(mode === "login" ? "账号或密码不正确。" : error instanceof ApiError && error.code === "USERNAME_TAKEN" ? "这个账号已经存在，请换一个账号。" : error instanceof ApiError && error.code === "AUTH_INVALID_PASSWORD" ? "密码至少需要 8 位，请换一个更安全的密码。" : "创建失败：请检查账号、密码和家庭信息。") } }}><label>账号<input aria-label="账号" value={username} onChange={event => setUsername(event.target.value)} /></label><label>密码<input aria-label="密码" type="password" minLength={mode === "register" ? 8 : undefined} value={password} onChange={event => setPassword(event.target.value)} />{mode === "register" && <small className="login-help">至少 8 位</small>}</label>{mode === "register" && <><label>家庭名称<input aria-label="家庭名称" value={familyName} onChange={event => setFamilyName(event.target.value)} placeholder="例如：李家观察室" /></label><label>第一个小朋友<input aria-label="第一个小朋友" value={childName} onChange={event => setChildName(event.target.value)} placeholder="例如：小满" /></label></>}<button type="submit">{mode === "login" ? "进入观察手册" : "创建家庭档案"}</button>{notice && <p role="status">{notice}</p>}</form><footer>{mode === "login" ? <>还没有家庭账号？<button onClick={() => { setMode("register"); setNotice(""); }}>创建家庭账号</button></> : <>已有账号？<button onClick={() => { setMode("login"); setNotice(""); }}>返回登录</button></>}</footer></section></main>;
}
